
DROP TABLE IF EXISTS `TB_ASMI_LOV_QUERIES`;
CREATE TABLE `TB_ASMI_LOV_QUERIES` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `QUERY_ID` VARCHAR(100) NOT NULL,
  `QUERY_STRING` VARCHAR(1000) NOT NULL,
  `DB_JNDI_NAME` VARCHAR(50) NOT NULL,
  `QUERY_TYPE` VARCHAR(3) DEFAULT 'SQL',
  `BINDVAR_COLS` VARCHAR(300) DEFAULT NULL,
  `BINDVAR_DATA_TYPES` VARCHAR(300) DEFAULT NULL,
  `FILTER_COLS` VARCHAR(300) DEFAULT NULL,
  `ORDERBY_COL` VARCHAR(40) DEFAULT NULL,
  `ORDERBY_TYPE` VARCHAR(5) DEFAULT 'ASC',
  `CREATE_TS` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `UPDATE_TS` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `CREATE_BY` VARCHAR(50) DEFAULT NULL,
  `SESSION_REQD` VARCHAR(1) DEFAULT NULL,
  `VERSION_NO` int(11) DEFAULT 1,
  PRIMARY KEY (`APP_ID`,`QUERY_ID`) 
) ;

DROP TABLE IF EXISTS `TB_ASMI_OS_DTLS`;
CREATE TABLE `TB_ASMI_OS_DTLS` (
  `OS_ID` VARCHAR(50) NOT NULL,
  `OS_DESC` VARCHAR(200) DEFAULT NULL,
  `CREATE_BY` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(11) DEFAULT 1,
  PRIMARY KEY (`OS_ID`)
 );




 DROP TABLE IF EXISTS `TB_ASNF_DEVICES_MASTER`;
CREATE TABLE `TB_ASNF_DEVICES_MASTER` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `NOTIF_REG_ID` VARCHAR(255) NOT NULL,
  `DEVICE_ID` VARCHAR(255) DEFAULT NULL,
  `DEVICE_NAME` VARCHAR(255) DEFAULT NULL,
  `OS_ID` VARCHAR(50) DEFAULT NULL,
  `OS_VERSION` VARCHAR(255) DEFAULT NULL,
  `STATUS` VARCHAR(20) DEFAULT NULL,
  `CREATED_BY` VARCHAR(255) DEFAULT NULL,
  `CREATED_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(11) DEFAULT 1,
  `MAKER_ID` VARCHAR(45),
  `MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `CHECKER_ID` VARCHAR(45),
  `CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `AUTH_STATUS` VARCHAR(45) DEFAULT 'U',
  `NOTIF_MSG_SERVER` VARCHAR(255) DEFAULT  NULL,
  PRIMARY KEY (`APP_ID`,`NOTIF_REG_ID`)
);

DROP TABLE IF EXISTS `TB_ASNF_GROUP_DEVICES`;
CREATE TABLE `TB_ASNF_GROUP_DEVICES` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `GROUP_ID` VARCHAR(255) NOT NULL,
  `NOTIF_REG_ID` VARCHAR(255) NOT NULL,
  `CREATED_BY` VARCHAR(255) DEFAULT NULL,
  `CREATED_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  PRIMARY KEY (`APP_ID`,`GROUP_ID`,`NOTIF_REG_ID`)
) ;

DROP TABLE IF EXISTS `TB_ASNF_GROUP_MASTER`;
CREATE TABLE `TB_ASNF_GROUP_MASTER` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `GROUP_ID` VARCHAR(255) NOT NULL,
  `GROUP_DESC` VARCHAR(500) DEFAULT NULL,
  `CREATED_BY` VARCHAR(50) DEFAULT NULL,
  `CREATED_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(11) DEFAULT 1,
  PRIMARY KEY (`APP_ID`,`GROUP_ID`)
) ;

DROP TABLE IF EXISTS `TB_ASNF_TXN_DEVICES`;
CREATE TABLE `TB_ASNF_TXN_DEVICES` (
  `NOTIF_ID` int(11) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `NOTIF_REG_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`NOTIF_ID`,`APP_ID`,`NOTIF_REG_ID`)
);

DROP TABLE IF EXISTS `TB_ASNF_TXN_GROUPS`;
CREATE TABLE `TB_ASNF_TXN_GROUPS` (
  `NOTIF_ID` int(11) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `GROUP_ID` VARCHAR(255) NOT NULL,
   PRIMARY KEY (`NOTIF_ID`,`APP_ID`,`GROUP_ID`)
) ;

DROP TABLE IF EXISTS `TB_ASNF_TXN_LOG`;
CREATE TABLE `TB_ASNF_TXN_LOG` (
  `NOTIF_ID` int(11) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `USER_ID` VARCHAR(100),
  `NOTIF_REG_ID` VARCHAR(255) NOT NULL,
  `DEVICE_ID` VARCHAR(255) NOT NULL,
  `STATUS` char(150) DEFAULT NULL,
  `CREATED_BY` VARCHAR(150) DEFAULT NULL,
  `CREATED_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(11) DEFAULT 1,
   PRIMARY KEY (`NOTIF_ID`,`APP_ID`,`NOTIF_REG_ID`,`DEVICE_ID`)
) ;

DROP TABLE IF EXISTS `TB_ASNF_TXN_MASTER`;
CREATE TABLE `TB_ASNF_TXN_MASTER` (
  `NOTIF_ID` int(11) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `NOTIF_MSG` VARCHAR(255) NOT NULL,
  `TITLE` VARCHAR(255),
  `SUBTITLE` VARCHAR(255),
  `IMAGE_URL` VARCHAR(255),
  `CATEGORY` VARCHAR(255),
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`NOTIF_ID`,`APP_ID`,`NOTIF_MSG`)
) ;


 DROP TABLE IF EXISTS `TB_ASTP_SEQ_GEN`;
CREATE TABLE `TB_ASTP_SEQ_GEN` (
  `SEQUENCE_NAME` VARCHAR(50) NOT NULL,
  `SEQUENCE_VALUE` int(11) NOT NULL,
  `CREATE_BY` VARCHAR(20) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(11) DEFAULT 1,
  PRIMARY KEY (`SEQUENCE_NAME`)
 );
 
 /*CREATE TABLE TB_AFTP_WORKFLOW_DET 
( 
  TRANSACTION_REF_NO VARCHAR(30) NOT NULL 
, VERSION_NO DECIMAL(10, 0) NOT NULL 
, WORKFLOW_ID VARCHAR(100) NOT NULL 
, CURRENT_STAGE VARCHAR(100) NOT NULL 
, SCREEN_ID VARCHAR(100) NOT NULL 
, NEXT_STAGE VARCHAR(100) NULL 
, STATUS VARCHAR(20) NULL 
, APP_ID VARCHAR(100) NOT NULL 
, INTERFACE_ID VARCHAR(100) NOT NULL 
, USER_ID VARCHAR(100) NULL 
, SCREEN_DATA LONGTEXT NULL 
, STAGE_SEQ_NO VARCHAR(255) NULL 
, ACTION VARCHAR(255) NULL 
, CREATE_USER_ID VARCHAR(100) NULL
, CREATE_TS TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3)
, CONSTRAINT PRIMARY KEY ( TRANSACTION_REF_NO, VERSION_NO, WORKFLOW_ID, CURRENT_STAGE, SCREEN_ID, APP_ID, INTERFACE_ID )
);
*/
 
 DROP TABLE IF EXISTS `TB_ASTP_WORKFLOW_DET`;
 CREATE TABLE `TB_ASTP_WORKFLOW_DET`
  (
    `TRANSACTION_REF_NO` VARCHAR(30) NOT NULL ,
    `VERSION_NO` DECIMAL(10, 0) NULL, 
   `WORKFLOW_ID`        VARCHAR(100) NOT NULL ,
   `APP_ID`             VARCHAR(100) NOT NULL ,
   `CURRENT_STAGE`       VARCHAR(100) NULL ,
    `SCREEN_ID`          VARCHAR(100) NULL ,
    `NEXT_STAGE`         VARCHAR(100) NULL ,
    `STATUS`             VARCHAR(20) NULL ,
    `INTERFACE_ID`        VARCHAR(100) NULL ,
   `USER_ID`             VARCHAR(100) NULL ,
    `SCREEN_DATA` longtext NULL ,
    `STAGE_SEQ_NO`   VARCHAR(255 ) NULL ,
    `ACTION`         VARCHAR(255 ) NULL ,
    `CREATE_USER_ID` VARCHAR(100 ) NULL ,
    `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) ,
    CONSTRAINT `TB_ASTP_WORKFLOW_DET_PK` PRIMARY KEY (`TRANSACTION_REF_NO`, `WORKFLOW_ID`, `APP_ID`)
  );

  DROP TABLE IF EXISTS `TB_ASMI_APP_DTLS`;
CREATE TABLE `TB_ASMI_APP_DTLS` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `OS_ID` VARCHAR(50) NOT NULL,
  `APP_DESC` VARCHAR(200) DEFAULT NULL,
  `CREATE_BY` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(11) DEFAULT 1,
  CONSTRAINT `TB_ASMI_APP_DTLS_PK` PRIMARY KEY (`APP_ID`,`OS_ID`)
) ;

DROP TABLE IF EXISTS `TB_ASFS_FILE_DETAILS`;
CREATE TABLE `TB_ASFS_FILE_DETAILS` 
( 
  `APP_ID` VARCHAR(100) NOT NULL 
, `SCREEN_ID` VARCHAR(100) NULL 
, `USER_ID` VARCHAR(100)  NULL 
, `FILE_NAME` VARCHAR(150)  NOT NULL  
, `FILE_TYPE` VARCHAR(20) NULL 
, `INTERFACE_ID` VARCHAR(30) NULL
, `CREATE_USER_ID` VARCHAR(100) NULL 
, `LAST_UPLOADED_DATE` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) 
, `RECENT_UPLOADED_DATE` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
, CONSTRAINT PRIMARY KEY ( `APP_ID`,`FILE_NAME`) 
);

/*
 * Changes made by Ripu
 * Below table added for FS item : Appzillon - 3.1 - 13, 15, 65 Start
 */

/* Appzillon - 3.1 - 13, 15, 65 END */

/*
 * Changes made by Ripu
 * Below tables added for (OTA) FS item : Appzillon - 3.1 - 13 Start
 */

DROP TABLE IF EXISTS `TB_ASMI_APP_USER`;
  CREATE TABLE `TB_ASMI_APP_USER`
   (	 
	`USER_ID` VARCHAR(50) NOT NULL, 
  	`PARENT_APP_ID` VARCHAR(100) NOT NULL,
	`CHILD_APP_ID` VARCHAR(100) NOT NULL, 
	`CREATE_USER_ID` VARCHAR(50), 
	`CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3), 
	`VERSION_NO` int(11) DEFAULT 1, 
	 CONSTRAINT `TB_ASMI_APP_USER_PK` PRIMARY KEY (`USER_ID`, `PARENT_APP_ID`, `CHILD_APP_ID`)
    ) ;
    
    
    DROP TABLE IF EXISTS `TB_ASMI_APP_FILES`;
  CREATE TABLE `TB_ASMI_APP_FILES` 
   (	
	`APP_ID` VARCHAR(100) NOT NULL, 
	`APP_VERSION` VARCHAR(10) NOT NULL,
    `OS` VARCHAR(20) NOT NULL,
    `FILE_NAME` VARCHAR(100) NOT NULL,
	`FILE_PATH` VARCHAR(255), 
	`ACTION` VARCHAR(10),
	`CREATE_USER_ID` VARCHAR(100), 
	`CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3), 
	`VERSION_NO` int(11) DEFAULT 1,
	CONSTRAINT `TB_ASMI_APP_FILES_PK` PRIMARY KEY (`APP_ID`, `APP_VERSION`, `OS`, `FILE_NAME`)
   ) ;
   

   DROP TABLE IF EXISTS `TB_ASMI_APP_OS_VERSION`;
  CREATE TABLE `TB_ASMI_APP_OS_VERSION`
   (	 
    `APP_ID` VARCHAR(100) NOT NULL, 
  	`OS` VARCHAR(20) NOT NULL,
    `APP_VERSION` VARCHAR(10) NOT NULL, 
    `CREATE_USER_ID` VARCHAR(50), 
    `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3), 
    `VERSION_NO` int(11) DEFAULT 1,
    `APP_ACTION` VARCHAR(10) NOT NULL DEFAULT 'IGNORE', 
    CONSTRAINT `TB_ASMI_APP_OS_VERSION_PK` PRIMARY KEY (`APP_ID`, `OS`, `APP_VERSION`)
    ) ;
    
    
 /* Appzillon - 3.1 - 13 END */
   
/* 
    * Changes Made By Ripu
    * Appzillon - 3.1 - Audit Log Start
    */
   
  
/* Appzillon - 3.1 - Send SMS to user End*/


/*
 * Changes done by Ripu
 * Appzillon - 3.1 - Task Repair Start
 */
/*CREATE TABLE `TB_AFHS_WORKFLOW_DET`
  (
    `TRANSACTION_REF_NO` VARCHAR(30) NOT NULL ,
    `VERSION_NO`         DECIMAL(10, 0) NOT NULL,
   `WORKFLOW_ID`        VARCHAR(100) NOT NULL ,
   `CURRENT_STAGE`       VARCHAR(100) NOT NULL ,
    `SCREEN_ID`          VARCHAR(100) NOT NULL ,
    `NEXT_STAGE`         VARCHAR(100) NULL ,
    `STATUS`             VARCHAR(20) NULL ,
    `APP_ID`             VARCHAR(100) NOT NULL ,
    `INTERFACE_ID`        VARCHAR(100) NOT NULL ,
   `USER_ID`             VARCHAR(100) NULL ,
    `SCREEN_DATA` longtext NULL ,
    `STAGE_SEQ_NO`   VARCHAR(255) NULL ,
    `ACTION`         VARCHAR(255) NULL ,
    `CREATE_USER_ID` VARCHAR(100) NULL ,
    `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) ,
    `HISTORY_VERSION_NO` INT(11) NOT NULL,
    CONSTRAINT `TB_AFHS_WORKFLOW_DET_PK` PRIMARY KEY (`TRANSACTION_REF_NO`, `VERSION_NO`, `WORKFLOW_ID`, `CURRENT_STAGE`,`SCREEN_ID` ,`APP_ID` ,`INTERFACE_ID`,`HISTORY_VERSION_NO` )
  );*/

DROP TABLE IF EXISTS `TB_ASHS_WORKFLOW_DET`;
CREATE TABLE `TB_ASHS_WORKFLOW_DET`
  (
    `TRANSACTION_REF_NO` VARCHAR(30) NOT NULL ,
    `VERSION_NO`         INT(11) NOT NULL,
   `WORKFLOW_ID`        VARCHAR(100) NOT NULL ,
   `APP_ID`             VARCHAR(100) NOT NULL ,
   `CURRENT_STAGE`       VARCHAR(100) NULL ,
    `SCREEN_ID`          VARCHAR(100) NULL ,
    `NEXT_STAGE`         VARCHAR(100) NULL ,
    `STATUS`             VARCHAR(20) NULL ,
    `INTERFACE_ID`        VARCHAR(100) NULL ,
   `USER_ID`             VARCHAR(100) NULL ,
    `SCREEN_DATA` longtext NULL ,
    `STAGE_SEQ_NO`   VARCHAR(255) NULL ,
    `ACTION`         VARCHAR(255) NULL ,
    `CREATE_USER_ID` VARCHAR(100) NULL ,
    `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) ,
    CONSTRAINT `TB_ASHS_WORKFLOW_DET_PK` PRIMARY KEY (`TRANSACTION_REF_NO`, `VERSION_NO`, `WORKFLOW_ID`, `APP_ID`)
  );
  /* Appzillon - 3.1 - Task Repair End*/
  

DROP TABLE IF EXISTS `TB_ASTP_BEACON_MASTER`;
CREATE TABLE `TB_ASTP_BEACON_MASTER` (
  `APP_ID` VARCHAR(100) DEFAULT NULL,
  `ID` BIGINT NOT NULL,
  `DEVICE_ID` VARCHAR(225) DEFAULT NULL,
  `USER_ID` VARCHAR(100) DEFAULT NULL,
  `ENTRY_TIME` TIMESTAMP(3) NULL DEFAULT NULL,
  `STATUS` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `TB_ASTP_OTP_ENGINE`;
CREATE TABLE `TB_ASTP_OTP_ENGINE` 
   (	
    `REF_NO` BIGINT NOT NULL, 
	`APP_ID` VARCHAR(100), 
	`USER_ID` VARCHAR(255), 
	`INTERFACE_ID` VARCHAR(255), 
	`SESSION_ID` VARCHAR(255), 
	`OTP` VARCHAR(255), 
  /*
  * OTP_GEN_TS ADDED NULL.
  * 
  */
	`OTP_GEN_TS` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`OTP_EXP_TS` TIMESTAMP(3) NULL,
	`OTP_STATUS` VARCHAR(255) DEFAULT 'N', 
	`OTP_VAL_TS` TIMESTAMP(3) NULL,
	`REQ_LD_REFNO` VARCHAR(100), 
	`REQ_NO_RECS` int(10), 
	`REQ_PAYLOAD_STATUS` VARCHAR(200), 
	`REQ_PAYLOAD_PROCESS_TS` TIMESTAMP(3) NULL,
	
  /*
  * Below Fields Added by sasidhar
  * 
  */
  `OTP_VALIDATION_COUNT` int(10),
  `OTP_RESENT_COUNT` int(10),
  `OTP_RESEND_LOCK` VARCHAR(1),
  `OTP_RESEND_LOCK_TS` TIMESTAMP(3) NULL,
  `OTP_REGEN_COUNT` int(10) DEFAULT 0,
  `VERSION_NO` int(10) NOT NULL DEFAULT 0,
  CONSTRAINT `TB_ASTP_OTP_ENGINE_PK` PRIMARY KEY (`REF_NO`)
   );

DROP TABLE IF EXISTS `TB_ASTP_AR_MASTER`;
CREATE TABLE `TB_ASTP_AR_MASTER` (
`APP_ID` VARCHAR(255) DEFAULT NULL,
`ID` BIGINT NOT NULL,
`REGION_CODE` VARCHAR(255) DEFAULT NULL,
`CATEGORY` VARCHAR(255) DEFAULT NULL,
`LATITUDE` VARCHAR(255) DEFAULT NULL,
`LONGITUDE` VARCHAR(255) DEFAULT NULL,
`TITLE`  VARCHAR(255) DEFAULT NULL,
`ADDITIONAL_INFO` VARCHAR(255) DEFAULT NULL,
`DESCRIPTION` VARCHAR(255) DEFAULT NULL,
`IMAGE` VARCHAR(255) DEFAULT NULL,
PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `TB_ASMI_SCHEDULER_JOB_EXP`;
CREATE TABLE `TB_ASMI_SCHEDULER_JOB_EXP` (
  `JOB_NAME` VARCHAR(45) NOT NULL,
  `START_DATE` VARCHAR(45) DEFAULT NULL,
  `END_DATE` VARCHAR(45) DEFAULT NULL,
  `EXP_START_SEC` VARCHAR(45) DEFAULT NULL,
  `EXP_SEC` VARCHAR(45) DEFAULT NULL,
  `EXP_MIN` VARCHAR(45) DEFAULT NULL,
  `EXP_HR` VARCHAR(45) DEFAULT NULL,
  `EXP_DOM` VARCHAR(45) DEFAULT NULL,
  `EXP_MONTH` VARCHAR(45) DEFAULT NULL,
  `EXP_DOW` VARCHAR(45) DEFAULT NULL,
  `EXP_YEAR` VARCHAR(45) DEFAULT NULL,
  `EXPRESSION` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`JOB_NAME`)
);

DROP TABLE IF EXISTS `TB_ASMI_SCHEDULER_JOB`;
CREATE TABLE `TB_ASMI_SCHEDULER_JOB` (
  `APP_ID` VARCHAR(45) DEFAULT NULL,
  `JOB_NAME` VARCHAR(255) NOT NULL,
  `JOB_CLASS` VARCHAR(255) DEFAULT NULL,
  `JOB_DATA` VARCHAR(255) DEFAULT NULL,
  `JOB_STATUS` VARCHAR(45) DEFAULT 'P',
  `JOB_CREATED_TS` TIMESTAMP(3) NULL DEFAULT NULL,
  `JOB_EXECUTED_TS` TIMESTAMP(3) NULL DEFAULT NULL,
  PRIMARY KEY (`JOB_NAME`)
);

DROP TABLE IF EXISTS `TB_OS`;
CREATE TABLE `TB_OS` (
  `OS_ID` varchar(15) NOT NULL,
  `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`OS_ID`)
);

DROP TABLE IF EXISTS `TB_ASMI_APP_ID_VERSION`;
  CREATE TABLE `TB_ASMI_APP_ID_VERSION`
   (	 
    `APP_ID` VARCHAR(100) NOT NULL,
    `OS` VARCHAR(20) NOT NULL,
  	`APP_ID_VERSION` VARCHAR(10) NOT NULL,
    `CREATE_USER_ID` VARCHAR(50), 
    `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3), 
    `VERSION_NO` int(11) DEFAULT 1,
    CONSTRAINT `TB_ASMI_APP_ID_VERSION_PK` PRIMARY KEY (`APP_ID`,`OS`,`APP_ID_VERSION`)
    ) ;

 
CREATE OR REPLACE VIEW VW_NOTIFY_APPID as select DISTINCT(APP_ID) appId from TB_ASNF_DEVICES_MASTER;

CREATE OR REPLACE VIEW VW_DIGITS AS
  SELECT 0 AS digit UNION ALL
  SELECT 1 UNION ALL
  SELECT 2 UNION ALL
  SELECT 3 UNION ALL
  SELECT 4 UNION ALL
  SELECT 5 UNION ALL
  SELECT 6 UNION ALL
  SELECT 7 UNION ALL
  SELECT 8 UNION ALL
  SELECT 9;

CREATE OR REPLACE VIEW VW_NUMBERS AS
  SELECT
    ones.digit + tens.digit * 10 + hundreds.digit * 100 + thousands.digit * 1000 AS number
  FROM
    VW_DIGITS as ones,
    VW_DIGITS as tens,
    VW_DIGITS as hundreds,
    VW_DIGITS as thousands;
    
CREATE OR REPLACE VIEW VW_DATES AS
  SELECT
    SUBDATE(CURRENT_DATE(), number) AS date
  FROM
    VW_NUMBERS;

CREATE OR REPLACE VIEW VW_OS_DATES as select d.date osdates,OS_ID AS datesos,appId from VW_DATES d,TB_OS o,VW_NOTIFY_APPID ap;

CREATE OR REPLACE VIEW VW_MESSAGE_STATS AS
select date(tnl.CREATED_TS) AS TXNDATE,count(0) AS num,tnm.OS_ID AS os,tnl.APP_ID AS appId
from TB_ASNF_TXN_LOG tnl,TB_ASNF_DEVICES_MASTER tnm
where (tnl.NOTIF_REG_ID = tnm.NOTIF_REG_ID) group by date(tnl.CREATED_TS),tnm.OS_ID,tnl.APP_ID;

CREATE OR REPLACE VIEW VW_MESSAGE_NOTIFY_STATS AS
SELECT VW_OS_DATES.appId,osdates,COALESCE(num,0) count,datesos 
FROM VW_MESSAGE_STATS RIGHT OUTER JOIN VW_OS_DATES ON osdates=TXNDATE 
AND datesos=os and VW_OS_DATES.appId=VW_MESSAGE_STATS.appId;

INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('ADMIN_DOMAIN',1,NULL,SYSDATE(),1);
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('GROUP_NO',1,NULL,SYSDATE(),1);
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('NOTIFICATION_NO',1,NULL,SYSDATE(),1);
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('TXNREF',1,NULL,SYSDATE(),1);
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('WORKFLOW',1,NULL,SYSDATE(),1);
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('JMS_TXN_ID',1,NULL,SYSDATE(),1);
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('ACCESS_REF',1,NULL,SYSDATE(),1);
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('BEACON_REF',1,NULL,SYSDATE(),1);
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('ISO8583_F11',1,NULL,SYSDATE(),1);
INSERT into TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) values ('OTP_REF_NO',1,NULL,SYSDATE(),1);
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('AR_REF',1,NULL,SYSDATE(),1);
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('SMS_TXNREF',1,NULL,SYSDATE(),1);
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('USSD_TXNREF',1,NULL,SYSDATE(),1);
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('TXT_TXNREF',1,NULL,SYSDATE(),1);
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('SOURCE_MSG_ID',1,NULL,SYSDATE(),1);
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('CAPTCHA_REF_NO',1,NULL,SYSDATE(),1);
	
INSERT INTO TB_OS (OS_ID,CREATE_TS) VALUES ('ANDROID',SYSDATE());
INSERT INTO TB_OS (OS_ID,CREATE_TS) VALUES ('IOS',SYSDATE());
INSERT INTO TB_OS (OS_ID,CREATE_TS) VALUES ('WINDOWS',SYSDATE());
 
DROP TABLE IF EXISTS `TB_ASMI_SECURITY_PARAMETERS`;
CREATE TABLE `TB_ASMI_SECURITY_PARAMETERS` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `MIN_NUM_NUM` int(10) DEFAULT NULL,
  `MIN_NUM_SPCL_CHAR` int(10) DEFAULT NULL,
  `MIN_NUM_UPPER_CASE_CHAR` int(10) DEFAULT NULL,
  `MIN_NUM_LOWER_CASE_CHAR` int(10) DEFAULT NULL,
  `MIN_LENGTH` int(10) DEFAULT NULL,
  `MAX_LENGTH` int(10) DEFAULT NULL,
  `PASS_CHANGE_FREQ` int(10) DEFAULT NULL,
  `LAST_N_PASS_NOT_TO_USE` int(10) DEFAULT NULL,
  `SESSION_TIMEOUT` int(10) DEFAULT NULL,
  `NOOFFAILEDCOUNTS` int(10) DEFAULT NULL,
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  `SERVER_TOKEN` VARCHAR(255) DEFAULT NULL,
  `FAIL_COUNT_TIMEOUT` int(10) DEFAULT NULL,
  `PASSWORD_COUNT` int(10) DEFAULT NULL,
  `DEFAULT_AUTHORIZATION` char(1) DEFAULT 'Y',
  `RESTRICT_SPL_CHARS` VARCHAR(100) DEFAULT NULL,
  /*
	 * Below Fields Added by ripu
	 * Appzillon - 3.1 - 65, 69 Start (for User creation extensibility and multifactor)
	 */
  `ALLOW_USER_PASSWORD_ENTRY` VARCHAR(1) DEFAULT 'N',
  `AUTO_APPROVE` VARCHAR(1) DEFAULT 'Y',
  `PWD_RSET_VALIDATE_PARAMS` VARCHAR(45) DEFAULT 'BOTH',
  `PWD_RSET_COMM_CHANNEL` VARCHAR(45) DEFAULT 'BOTH',
  `PWD_RSET_ACCEPT_USR_PWD` VARCHAR(1) DEFAULT 'N',
  `TXN_LOG_REQ` VARCHAR(45) DEFAULT 'Y',
  `MAKER_ID` VARCHAR(45),
  `MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `CHECKER_ID` VARCHAR(45),
  `CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `PWD_COMM_CHANNEL` VARCHAR(45) DEFAULT 'BOTH',
  `AUTH_STATUS` VARCHAR(45) DEFAULT 'U',
  /* Appzillon - 3.1 - 65, 69 End*/
  `MULTIPLE_SESSION_ALLOWED` VARCHAR(1) DEFAULT 'Y',
  `TXN_LOG_PAYLOAD` VARCHAR(10) DEFAULT 'NONE',
  `FMW_TXN_REQ` VARCHAR(1) DEFAULT 'Y',
  `FMW_TXN_PAYLOAD` VARCHAR(10) DEFAULT 'NONE',
  /*
   * Below Fields Added by sasidhar
   * Appzillon - for otp resend(yes,no) and otp type(numeric,string,aplhanumeric)
   */
   `OTP_LENGTH` int(10) DEFAULT NULL,
   `OTP_VALIDATION_COUNT` int(10) DEFAULT NULL,
   `OTP_EXPIRY` int(10) DEFAULT NULL,
   `OTP_RESEND` VARCHAR(10) DEFAULT NULL,
   `OTP_FORMAT` VARCHAR(20) DEFAULT NULL,
   `OTP_RESEND_COUNT` int(10) DEFAULT NULL ,
   `OTP_RESEND_LOCK_TIMEOUT` int(10) DEFAULT NULL ,
   `OTP_REGEN_COUNT` int(10) DEFAULT 0,
   `PWD_CHANGE_COMM_CHANNEL` VARCHAR(30) DEFAULT 'BOTH',
   `PASSWORD_ON_AUTHORIZATION` VARCHAR(1) DEFAULT 'N',
   `DATA_INTEGRITY` VARCHAR(1) DEFAULT 'Y',
   `ACCESS_TOKEN_EXPIRY` int(10) DEFAULT 0,
   /* changes end */
  PRIMARY KEY (`APP_ID`)
);

 DROP TABLE IF EXISTS `TB_ASLG_JMS_REQ_RESP`;
CREATE TABLE `TB_ASLG_JMS_REQ_RESP` (
  `TRANS_ID` BIGINT NOT NULL,
  `INTERFACE_ID` VARCHAR(150) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `REQ_TYPE` VARCHAR(150) NOT NULL,
  `RES_TYPE` VARCHAR(150) NOT NULL,
  `SENT_DATE` datetime NOT NULL,
  `RECEIVED_DATE` datetime DEFAULT NULL,
  `MSG_ID` VARCHAR(250) NOT NULL,
  `REQ_Q` VARCHAR(250) DEFAULT NULL,
  `RESP_Q` VARCHAR(250) DEFAULT NULL,
  `MSG_STATUS` int(1) NOT NULL,
  `MSG_SENT` longtext NOT NULL,
  `MSG_RECEIVED` longtext,
  `RESP_DESC` VARCHAR(250) DEFAULT NULL,
  PRIMARY KEY (`TRANS_ID`),
  UNIQUE KEY `TB_ASLG_JMS_REQ_RESP_LOG_UK1` (`MSG_ID`)
) ;
DROP TABLE IF EXISTS `TB_ASHS_USER_PASSWORDS`;
CREATE TABLE `TB_ASHS_USER_PASSWORDS` (
  `USER_ID` VARCHAR(100) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `PIN` VARCHAR(255) NOT NULL,
  `CHANGE_TIME` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  PRIMARY KEY (`USER_ID`,`APP_ID`,`PIN`)
 ) ;
 DROP TABLE IF EXISTS `TB_ASLG_TXN_DETAIL`;
CREATE TABLE `TB_ASLG_TXN_DETAIL` (
`TXN_REF` VARCHAR(255) NOT NULL,
`USER_ID` VARCHAR(100) DEFAULT NULL,
`USER_APP_ID` VARCHAR(100) DEFAULT NULL,
`APP_USER_ID` VARCHAR(100) DEFAULT NULL,
`SESSION_ID` VARCHAR(255) DEFAULT NULL,
`DEVICE_ID` VARCHAR(255) DEFAULT NULL,
`ST_TM` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
`END_TM` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
`INTERFACE_ID` VARCHAR(50) DEFAULT NULL,
`APP_ID` VARCHAR(100) DEFAULT NULL,
`TXN_STAT` VARCHAR(20) DEFAULT NULL,
`REQ_LD_REFNO` VARCHAR(100), 
`REQ_NO_RECS` int(10), 
`RES_LD_REFNO` VARCHAR(100), 
`RES_NO_RECS` int(10), 
`INFO1` VARCHAR(255) DEFAULT NULL,
`INFO2` VARCHAR(255) DEFAULT NULL,
`INFO3` VARCHAR(255) DEFAULT NULL,
`INFO4` VARCHAR(255) DEFAULT NULL,
`INFO5` VARCHAR(255) DEFAULT NULL,
`CREATE_BY` VARCHAR(200) DEFAULT NULL,
`SOURCE` VARCHAR(255),
`LONGITUDE` VARCHAR(255),
`LATITUDE` VARCHAR(255),
`ORIGINATION` VARCHAR(255),
`STATUS` VARCHAR(255),
`SUBLOCALITY` VARCHAR(255),
`ADMIN_AREA_LVL_1` VARCHAR(255),
`ADMIN_AREA_LVL_2` VARCHAR(255),
`COUNTRY` VARCHAR(255),
`FORMATTED_ADDRESS` VARCHAR(255),
`EXT_ST_TM` TIMESTAMP(3) NULL DEFAULT NULL,
`EXT_END_TM` TIMESTAMP(3) NULL DEFAULT NULL,
`CREATE_TS` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), 
PRIMARY KEY (`TXN_REF`) 
) ;

DROP TABLE IF EXISTS `TB_ASTP_LD_RECS`;

CREATE TABLE `TB_ASTP_LD_RECS` (
`REF_NO` varchar(100),
`SEQ_NO` INT(10),
`DATA1` varchar(255) DEFAULT NULL,
`DATA2` varchar(255) DEFAULT NULL,
`DATA3` varchar(255) DEFAULT NULL,
`DATA4` varchar(255) DEFAULT NULL,
`DATA5` varchar(255) DEFAULT NULL,
`CREATE_TS` timestamp(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
 PRIMARY KEY (`REF_NO`,`SEQ_NO`)

);

 DROP TABLE IF EXISTS `TB_ASLG_FMW_TXN_DETAIL`;
CREATE TABLE `TB_ASLG_FMW_TXN_DETAIL` (
  `TXN_REF` VARCHAR(255) NOT NULL,
  `MASTER_TXN_REF` VARCHAR(255),
  `INTERFACE_ID` VARCHAR(50),
  `REQ_LD_REFNO` VARCHAR(100), 
  `REQ_NO_RECS` int(10), 
  `RES_LD_REFNO` VARCHAR(100), 
  `RES_NO_RECS` int(10),
  `ENDPOINT_TYPE` VARCHAR(255),
  `ST_TM` TIMESTAMP(3) NULL DEFAULT NULL,
  `END_TM` TIMESTAMP(3) NULL DEFAULT NULL,
  `STATUS` VARCHAR(1),
  `CREATE_TS` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`TXN_REF`)
) ;

DROP TABLE IF EXISTS `TB_ASMI_INTF_MASTER`;
CREATE TABLE `TB_ASMI_INTF_MASTER` (
  `INTERFACE_ID` VARCHAR(100) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `CATEGORY` VARCHAR(30) DEFAULT NULL,
  `TYPE` VARCHAR(30) DEFAULT NULL,
  `DESCRIPTION` VARCHAR(100) DEFAULT NULL,
  `AUTHRZ_REQ` VARCHAR(1) DEFAULT 'Y',
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  `MAKER_ID` VARCHAR(45),
  `MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `CHECKER_ID` VARCHAR(45),
  `CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `AUTH_STATUS` VARCHAR(1) DEFAULT 'U', 
  `CAPTCHA_REQ` VARCHAR(5) DEFAULT 'TEXT',
  `CAPTCHA_TYPE` VARCHAR(7) DEFAULT 'N',
  `INTERFACE_DEF` LONGTEXT DEFAULT NULL,
  `DG_TXN_LOG_REQ` VARCHAR(1) DEFAULT 'Y',
  `TXN_LOG_REQ` VARCHAR(1) DEFAULT 'Y',
  `TXN_LOG_PAYLOAD_REQ` VARCHAR(10) DEFAULT 'NONE',
  `FMW_TXN_REQ` VARCHAR(1) DEFAULT 'Y',
  `FMW_TXN_PAYLOAD_REQ` VARCHAR(10) DEFAULT 'NONE',
  PRIMARY KEY (`INTERFACE_ID`,`APP_ID`)
 ) ;
DROP TABLE IF EXISTS `TB_ASMI_ROLE_INTF`;
CREATE TABLE `TB_ASMI_ROLE_INTF` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `ROLE_ID` VARCHAR(100) NOT NULL,
  `INTERFACE_ID` VARCHAR(100) NOT NULL,
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  PRIMARY KEY (`APP_ID`,`ROLE_ID`,`INTERFACE_ID`)
) ;

DROP TABLE IF EXISTS `TB_ASMI_ROLE_MASTER`;
CREATE TABLE `TB_ASMI_ROLE_MASTER` (
  `ROLE_ID` VARCHAR(255) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `ROLE_DESC` VARCHAR(255) DEFAULT NULL,
  `INTERFACE_ALLOWED` VARCHAR(1) DEFAULT 'A',
  `SCREEN_ALLOWED` VARCHAR(1) DEFAULT 'A',
  `CONTROL_ALLOWED` VARCHAR(1) DEFAULT 'A',
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  `MAKER_ID` VARCHAR(45),
  `MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `CHECKER_ID` VARCHAR(45),
  `CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `AUTH_STATUS` VARCHAR(1) DEFAULT 'U',
  PRIMARY KEY (`ROLE_ID`,`APP_ID`) 
) ;

DROP TABLE IF EXISTS `TB_ASMI_ROLE_SCR`;
CREATE TABLE `TB_ASMI_ROLE_SCR` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `SCREEN_ID` VARCHAR(100) NOT NULL,
  `ROLE_ID` VARCHAR(100) NOT NULL,
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  PRIMARY KEY (`APP_ID`,`ROLE_ID`,`SCREEN_ID`) 
);

DROP TABLE IF EXISTS `TB_ASMI_SCR_MASTER`;
CREATE TABLE `TB_ASMI_SCR_MASTER` (
  `SCREEN_ID` VARCHAR(255) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `SCREEN_DESC` VARCHAR(255) DEFAULT NULL,
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  `MAKER_ID` VARCHAR(45),
  `MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `CHECKER_ID` VARCHAR(45),
  `CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `AUTH_STATUS` VARCHAR(45) DEFAULT 'U',
  `SCREEN_TYPE` VARCHAR(10) DEFAULT NULL,
  `SCREEN_NAME` VARCHAR(100) DEFAULT NULL,
  `SCREEN_ICON` longtext,
  `CUSTOMISABLE` VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (`SCREEN_ID`,`APP_ID`)
 ) ;
DROP TABLE IF EXISTS `TB_ASMI_USER`;
CREATE TABLE `TB_ASMI_USER` (
  `USER_ID` VARCHAR(100) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `PIN` VARCHAR(300) DEFAULT NULL,
  `USER_NAME` VARCHAR(100) DEFAULT NULL,
   `LAST_NAME` VARCHAR(100) DEFAULT NULL,
  `LOGIN_STATUS` VARCHAR(3) NOT NULL,
  `FAIL_COUNT` int(10) DEFAULT NULL,
  `USER_ACTIVE` VARCHAR(3) DEFAULT 'Y',
  `USER_LOCKED` VARCHAR(3) DEFAULT 'N',
  `LANGUAGE` VARCHAR(2) DEFAULT 'en',
  `EXTERNALIDENTIFIER` VARCHAR(30) DEFAULT NULL,
  `USER_ADDR1` VARCHAR(50) DEFAULT NULL,
  `USER_ADDR2` VARCHAR(50) DEFAULT NULL,
  `USER_ADDR3` VARCHAR(50) DEFAULT NULL,
  `USER_ADDR4` VARCHAR(50) DEFAULT NULL,
  `USER_EML1` VARCHAR(255) DEFAULT NULL,
  `USER_EML2` VARCHAR(255) DEFAULT NULL,
  `USER_PHNO1` VARCHAR(20) DEFAULT NULL,
  `USER_PHNO2` VARCHAR(20) DEFAULT NULL,
  `USER_LVL` int(11) DEFAULT NULL,
  `USER_LOCK_TS` TIMESTAMP(3) NULL DEFAULT NULL,
  `PIN_CHANGE_TS` TIMESTAMP(3) NULL DEFAULT NULL,
  `PROFILE_PIC` mediumtext,
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  `MAKER_ID` VARCHAR(45),
  `MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `CHECKER_ID` VARCHAR(45),
  `DATE_OF_BIRTH` DATE,
  `CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `AUTH_STATUS` VARCHAR(45) DEFAULT 'U',
  `ADD_INFO1` VARCHAR(255),
  `ADD_INFO2` VARCHAR(255),
  `ADD_INFO3` VARCHAR(255),
  `ADD_INFO4` VARCHAR(255),
  `ADD_INFO5` VARCHAR(255),
  PRIMARY KEY (`USER_ID`,`APP_ID`)
) ;

DROP TABLE IF EXISTS `TB_ASMI_USER_DEVICES`;
CREATE TABLE `TB_ASMI_USER_DEVICES` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `DEVICE_ID` VARCHAR(250) NOT NULL,
  `USER_ID` VARCHAR(100) NOT NULL,
  `NOTIF_REG_ID` VARCHAR(255),
  `DEVICE_STATUS` VARCHAR(100) DEFAULT NULL,
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `MAKER_ID` VARCHAR(45),
  `MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `CHECKER_ID` VARCHAR(45),
  `CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `AUTH_STATUS` VARCHAR(45) DEFAULT 'U',
  `VERSION_NO` int(10) DEFAULT 1,
  PRIMARY KEY (`APP_ID`,`DEVICE_ID`,`USER_ID`)
 ) ;

 DROP TABLE IF EXISTS `TB_ASMI_USER_ROLE`;
CREATE TABLE `TB_ASMI_USER_ROLE` (
  `USER_ID` VARCHAR(100) NOT NULL,
  `ROLE_ID` VARCHAR(100) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  PRIMARY KEY (`USER_ID`,`ROLE_ID`,`APP_ID`)
 ) ;
DROP TABLE IF EXISTS `TB_ASTP_LAST_LOGIN`;
CREATE TABLE `TB_ASTP_LAST_LOGIN` (
  `USER_ID` VARCHAR(100) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `DEVICE_ID` VARCHAR(255) NOT NULL,
  `REQUEST_KEY` VARCHAR(255) DEFAULT NULL,
  `SESSION_ID` VARCHAR(255) DEFAULT NULL,
  `LAST_REQ_TIME` TIMESTAMP(3) NULL DEFAULT NULL,
  `LOGIN_TIME` TIMESTAMP(3) NULL DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  `OTP` VARCHAR(200) DEFAULT NULL,
  `OTP_GENERATION_TIME` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `OTP_STATUS` VARCHAR(1) DEFAULT NULL,
  `OTP_VALIDATION_COUNT` int(10) DEFAULT 0,
  `LONGITUDE` VARCHAR(255),
  `LATITUDE` VARCHAR(255),
   `SUBLOCALITY` VARCHAR(255),
    `ADMIN_AREA_LVL_1` VARCHAR(255),
    `ADMIN_AREA_LVL_2` VARCHAR(255),
    `COUNTRY` VARCHAR(255),
    `FORMATTED_ADDRESS` VARCHAR(255),
  `ORIGINATION` VARCHAR(255),
  PRIMARY KEY (`USER_ID`,`APP_ID`,`DEVICE_ID`)
 ) ;
DROP TABLE IF EXISTS `TB_ASMI_DEVICE_MASTER`;
CREATE TABLE `TB_ASMI_DEVICE_MASTER`(
	`APP_ID` VARCHAR(100) NOT NULL,
	`DEVICE_ID` VARCHAR(200) NOT NULL,
	`OS` VARCHAR(20) NULL,
	`OS_VERSION` VARCHAR(50) NULL,
	`MOBILE_NUMBER1` VARCHAR(20) NULL,
	`MOBILE_NUMBER2` VARCHAR(20) NULL,
	`MODEL` VARCHAR(100) NULL,
	`MAKE` VARCHAR(100) NULL,
	`SCREEN_RESOLUTION` VARCHAR(100) NULL,
	`WIPED_OUT` VARCHAR(1) DEFAULT 'N',
	`CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	`DEVICE_NAME` VARCHAR(100) NULL,
	`LONGITUDE` VARCHAR(100) NULL,
	`LATITUDE` VARCHAR(100) NULL,
	`APP_VERSION` VARCHAR(50) NULL,
	CONSTRAINT TB_ASMI_DEVICE_MASTER_PK PRIMARY KEY (APP_ID, DEVICE_ID)
);
 DROP TABLE IF EXISTS `TB_ASLG_AUDIT_LOG`;
    CREATE TABLE `TB_ASLG_AUDIT_LOG`
  (
    `ACCESS_REF`     BIGINT NOT NULL,
    `APP_ID`         VARCHAR(100)  NULL,
    `USER_ID`        VARCHAR(100) NULL,
    `DEVICE_ID`      VARCHAR(250)  NULL,
    `SESSION_ID`     VARCHAR(100) NULL,
    `ACTION`         VARCHAR(30) NULL,
    `START_TIME_STAMP` VARCHAR(30) NULL,
    `END_TIME_STAMP` VARCHAR(30) NULL,
    `FIELD1`         VARCHAR(100) NULL,
    `FIELD2`         VARCHAR(100) NULL,
    `FIELD3`         VARCHAR(100) NULL,
    `FIELD4`         VARCHAR(100) NULL,
    `FIELD5`         VARCHAR(100) NULL,
    `CREATE_DATE` DATE DEFAULT null,
    `CREATE_USER_ID` VARCHAR(100) NULL,
    `VERSION_NO` int(11) DEFAULT 1,
    CONSTRAINT `PK_TB_ASLG_AUDIT_LOG` PRIMARY KEY ( `ACCESS_REF`  )
  );
  /* Appzillon - 3.1 - Audit Log End */
  
  /*
   * Changes done by Ripu on (10-Feb-2015)
   * Appzillon - 3.1 - Send SMS to User Start
   */
  
  DROP TABLE IF EXISTS `TB_ASMI_SMS_USER`;
 CREATE TABLE `TB_ASMI_SMS_USER`(
  `APP_ID` VARCHAR(100) NOT NULL,
  `USER_ID` VARCHAR(100) NOT NULL,
  `MOBILE_NUMBER` VARCHAR(20),
  `CREATED_BY` VARCHAR(50), 
  `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3), 
  `VERSION_NO` int(11) DEFAULT 1, 
  `SMS_REQ` VARCHAR(1),
  `USSD_REQ` VARCHAR(1),
  PRIMARY KEY(`APP_ID`, `USER_ID`)
);

DROP TABLE IF EXISTS `TB_ASLG_SMS_TXN`;
CREATE TABLE `TB_ASLG_SMS_TXN` 
   (           
                `SMS_TXNREF` VARCHAR(255) NOT NULL,
                `APP_ID` VARCHAR(100),
                `MOBILE_NUMBER` VARCHAR(20), 
                `REQUEST` VARCHAR(4000),
                `MESSAGE_ID` VARCHAR(20), 
                `ORIGINATION` VARCHAR(20), 
                `START_TM` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), 
				`RESPONSE` VARCHAR(4000),
				`END_TM` TIMESTAMP(3) NULL ON UPDATE CURRENT_TIMESTAMP(3), 
                `CREATED_BY` VARCHAR(20), 
                `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
                PRIMARY KEY (`SMS_TXNREF`) 
   ) ;
   
   DROP TABLE IF EXISTS `TB_ASLG_USSD_TXN`;
   CREATE TABLE `TB_ASLG_USSD_TXN` 
   (           
                `USSD_TXNREF` VARCHAR(255) NOT NULL,
                `APP_ID` VARCHAR(100),
                `MOBILE_NUMBER` VARCHAR(20),
                `REQUEST` VARCHAR(200), 
				`ACTION` VARCHAR(3000),
				`STEP` VARCHAR(100),
                `ORIGINATION` VARCHAR(20), 
                `START_TM` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
				`RESPONSE` VARCHAR(200),
				`END_TM` TIMESTAMP(3) NULL ON UPDATE CURRENT_TIMESTAMP(3),
                `CREATED_BY` VARCHAR(20), 
                `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
                PRIMARY KEY (`USSD_TXNREF`) 
   ) ;
   
   DROP TABLE IF EXISTS `TB_ASLG_TXT_MSLG_LOG`;
   CREATE TABLE `TB_ASLG_TXT_MSLG_LOG` 
   (           
                `TXT_TXNREF` VARCHAR(255) NOT NULL, 
                `APP_ID` VARCHAR(100),
                `MOBILE_NUMBER` VARCHAR(20),
                `REQUEST` TEXT, 
                `PORT` VARCHAR(10),
                `ORIGINATION` VARCHAR(20), 
                `START_TM` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
                `RESPONSE` VARCHAR(200),
                `END_TM` TIMESTAMP(3) NULL ON UPDATE CURRENT_TIMESTAMP(3),
                `CREATED_BY` VARCHAR(20), 
                `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
                PRIMARY KEY (`TXT_TXNREF`) 
   ) ;
   
   DROP TABLE IF EXISTS `TB_ASMI_CONTROLS_MASTER`;
   CREATE TABLE `TB_ASMI_CONTROLS_MASTER` (
   `APP_ID` VARCHAR(100) NOT NULL,
   `CONTROL_ID` VARCHAR(255) NOT NULL,
   `CONTROL_DESC` VARCHAR(255) DEFAULT NULL,
   `CREATED_BY` VARCHAR(100) DEFAULT NULL,
   `CREATED_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
   `MAKER_ID` VARCHAR(45),
   `MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
   `CHECKER_ID` VARCHAR(45),
   `CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
   `AUTH_STATUS` VARCHAR(45) DEFAULT 'U',
   `VERSION_NO` int(10) DEFAULT 1,
   PRIMARY KEY (`APP_ID`,`CONTROL_ID`)
  ) ;

DROP TABLE IF EXISTS `TB_ASMI_ROLE_CONTROLS`;
CREATE TABLE `TB_ASMI_ROLE_CONTROLS` (
   `APP_ID` VARCHAR(100) NOT NULL,
   `ROLE_ID` VARCHAR(100) NOT NULL,
   `CONTROL_ID` VARCHAR(100) NOT NULL,
   `CREATED_BY` VARCHAR(100) DEFAULT NULL,
   `CREATED_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
   `VERSION_NO` int(10) DEFAULT 1,
   PRIMARY KEY (`APP_ID`,`ROLE_ID`,`CONTROL_ID`)
) ;
DROP TABLE IF EXISTS `TB_ASHS_USER`;
CREATE TABLE `TB_ASHS_USER` (
  `USER_ID` VARCHAR(100) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `PIN` VARCHAR(300) DEFAULT NULL,
  `USER_NAME` VARCHAR(100) DEFAULT NULL,
  `LAST_NAME` VARCHAR(100) DEFAULT NULL,
  `LOGIN_STATUS` VARCHAR(3) NOT NULL,
  `FAIL_COUNT` int(10) DEFAULT NULL,
  `USER_ACTIVE` VARCHAR(3) DEFAULT 'Y',
  `USER_LOCKED` VARCHAR(3) DEFAULT 'N',
  `LANGUAGE` VARCHAR(2) DEFAULT 'en',
  `EXTERNALIDENTIFIER` VARCHAR(30) DEFAULT NULL,
  `USER_ADDR1` VARCHAR(50) DEFAULT NULL,
  `USER_ADDR2` VARCHAR(50) DEFAULT NULL,
  `USER_ADDR3` VARCHAR(50) DEFAULT NULL,
  `USER_ADDR4` VARCHAR(50) DEFAULT NULL,
  `USER_EML1` VARCHAR(255) DEFAULT NULL,
  `USER_EML2` VARCHAR(255) DEFAULT NULL,
  `USER_PHNO1` VARCHAR(20) DEFAULT NULL,
  `USER_PHNO2` VARCHAR(20) DEFAULT NULL,
  `USER_LVL` int(11) DEFAULT NULL,
  `USER_LOCK_TS` TIMESTAMP(3) NULL DEFAULT NULL,
  `PIN_CHANGE_TS` TIMESTAMP(3) NULL DEFAULT NULL,
  `PROFILE_PIC` mediumtext,
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  `MAKER_ID` VARCHAR(45),
  `MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `CHECKER_ID` VARCHAR(45),
  `DATE_OF_BIRTH` DATE,
  `CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `AUTH_STATUS` VARCHAR(45) DEFAULT 'U',
  `ADD_INFO1` VARCHAR(255),
  `ADD_INFO2` VARCHAR(255),
  `ADD_INFO3` VARCHAR(255),
  `ADD_INFO4` VARCHAR(255),
  `ADD_INFO5` VARCHAR(255),
  PRIMARY KEY (`USER_ID`,`APP_ID`,`VERSION_NO`)
) ;


DROP TABLE IF EXISTS `TB_ASHS_USER_DEVICES`;
CREATE TABLE `TB_ASHS_USER_DEVICES` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `DEVICE_ID` VARCHAR(250) NOT NULL,
  `USER_ID` VARCHAR(100) NOT NULL,
  `DEVICE_STATUS` VARCHAR(100) DEFAULT NULL,
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `MAKER_ID` VARCHAR(45),
  `MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `CHECKER_ID` VARCHAR(45),
  `CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `AUTH_STATUS` VARCHAR(45) DEFAULT 'U',
  `VERSION_NO` int(10) DEFAULT 1,
  PRIMARY KEY (`APP_ID`,`DEVICE_ID`,`USER_ID`,`VERSION_NO`)
 ) ;

 DROP TABLE IF EXISTS `TB_ASHS_USER_ROLE`;
CREATE TABLE `TB_ASHS_USER_ROLE` (
  `USER_ID` VARCHAR(100) NOT NULL,
  `ROLE_ID` VARCHAR(100) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  PRIMARY KEY (`USER_ID`,`ROLE_ID`,`APP_ID`,`VERSION_NO`)
 ) ;

   DROP TABLE IF EXISTS `TB_ASHS_SMS_USER`;
 CREATE TABLE `TB_ASHS_SMS_USER`(
  `APP_ID` VARCHAR(100) NOT NULL,
  `MOBILE_NUMBER` VARCHAR(20),
  `USER_ID` VARCHAR(100) NOT NULL,
  `CREATED_BY` VARCHAR(50), 
  `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3), 
  `VERSION_NO` int(11) DEFAULT 1, 
  `SMS_REQ` VARCHAR(1),
  `USSD_REQ` VARCHAR(1),
  CONSTRAINT `TB_ASHS_SMS_USER_PK` PRIMARY KEY(`APP_ID`, `USER_ID`,`VERSION_NO`)
);
DROP TABLE IF EXISTS `TB_ASHS_SECURITY_PARAMETERS`;
CREATE TABLE `TB_ASHS_SECURITY_PARAMETERS` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `MIN_NUM_NUM` int(10) DEFAULT NULL,
  `MIN_NUM_SPCL_CHAR` int(10) DEFAULT NULL,
  `MIN_NUM_UPPER_CASE_CHAR` int(10) DEFAULT NULL,
  `MIN_LENGTH` int(10) DEFAULT NULL,
  `MAX_LENGTH` int(10) DEFAULT NULL,
  `PASS_CHANGE_FREQ` int(10) DEFAULT NULL,
  `LAST_N_PASS_NOT_TO_USE` int(10) DEFAULT NULL,
  `SESSION_TIMEOUT` int(10) DEFAULT NULL,
  `NOOFFAILEDCOUNTS` int(10) DEFAULT NULL,
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  `SERVER_TOKEN` VARCHAR(255) DEFAULT NULL,
  `FAIL_COUNT_TIMEOUT` int(10) DEFAULT NULL,
  `PASSWORD_COUNT` int(10) DEFAULT NULL,
  `DEFAULT_AUTHORIZATION` char(1) DEFAULT 'Y',
  `RESTRICT_SPL_CHARS` VARCHAR(100) DEFAULT NULL,
   `ALLOW_USER_PASSWORD_ENTRY` VARCHAR(1) DEFAULT 'N',
  `AUTO_APPROVE` VARCHAR(1) DEFAULT 'Y',
  `PWD_RSET_VALIDATE_PARAMS` VARCHAR(45) DEFAULT 'BOTH',
  `PWD_RSET_COMM_CHANNEL` VARCHAR(45) DEFAULT 'BOTH',
  `PWD_RSET_ACCEPT_USR_PWD` VARCHAR(1) DEFAULT 'N',
  `TXN_LOG_REQ` VARCHAR(45) DEFAULT 'Y',
  `MAKER_ID` VARCHAR(45),
  `MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `CHECKER_ID` VARCHAR(45),
  `CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `PWD_COMM_CHANNEL` VARCHAR(45) DEFAULT 'BOTH',
  `AUTH_STATUS` VARCHAR(45) DEFAULT 'U',
  /* Appzillon - 3.1 - 65, 69 End*/
  `MULTIPLE_SESSION_ALLOWED` VARCHAR(1) DEFAULT 'Y',
  `TXN_LOG_PAYLOAD` VARCHAR(1) DEFAULT 'Y',
   `OTP_LENGTH` int(10) DEFAULT NULL,
   `OTP_VALIDATION_COUNT` int(10) DEFAULT NULL,
   `OTP_EXPIRY` int(10) DEFAULT NULL,
   `OTP_RESEND` VARCHAR(10) DEFAULT NULL,
   `OTP_FORMAT` VARCHAR(20) DEFAULT NULL,
   `OTP_RESEND_COUNT` int(10) DEFAULT NULL ,
   `OTP_RESEND_LOCK_TIMEOUT` int(10) DEFAULT NULL ,
   `PWD_CHANGE_COMM_CHANNEL` VARCHAR(30) DEFAULT 'BOTH',
   `PASSWORD_ON_AUTHORIZATION` VARCHAR(1) DEFAULT 'N',
   `DATA_INTEGRITY` VARCHAR(1) DEFAULT 'Y',
   `ACCESS_TOKEN_EXPIRY` int(10) DEFAULT 0,
  PRIMARY KEY (`APP_ID`,`VERSION_NO`)
);

DROP TABLE IF EXISTS `TB_ASHS_ROLE_MASTER`;
CREATE TABLE `TB_ASHS_ROLE_MASTER` (
  `ROLE_ID` VARCHAR(255) NOT NULL,
  `APP_ID` VARCHAR(100) NOT NULL,
  `ROLE_DESC` VARCHAR(255) DEFAULT NULL,
  `INTERFACE_ALLOWED` VARCHAR(1) DEFAULT 'A',
  `SCREEN_ALLOWED` VARCHAR(1) DEFAULT 'A',
  `CONTROL_ALLOWED` VARCHAR(1) DEFAULT 'A',
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  `MAKER_ID` VARCHAR(45),
  `MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `CHECKER_ID` VARCHAR(45),
  `CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `AUTH_STATUS` VARCHAR(45) DEFAULT 'U',
  PRIMARY KEY (`ROLE_ID`,`APP_ID`,`VERSION_NO`) 
) ;

DROP TABLE IF EXISTS `TB_ASHS_ROLE_SCR`;
CREATE TABLE `TB_ASHS_ROLE_SCR` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `SCREEN_ID` VARCHAR(100) NOT NULL,
  `ROLE_ID` VARCHAR(100) NOT NULL,
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  PRIMARY KEY (`APP_ID`,`ROLE_ID`,`SCREEN_ID`,`VERSION_NO`) 
);
DROP TABLE IF EXISTS `TB_ASHS_ROLE_INTF`;
CREATE TABLE `TB_ASHS_ROLE_INTF` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `ROLE_ID` VARCHAR(100) NOT NULL,
  `INTERFACE_ID` VARCHAR(100) NOT NULL,
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  PRIMARY KEY (`APP_ID`,`ROLE_ID`,`INTERFACE_ID`,`VERSION_NO`)
) ;

DROP TABLE IF EXISTS `TB_ASMI_APP_ACCESS_TOKEN`;
CREATE TABLE `TB_ASMI_APP_ACCESS_TOKEN` (
`APP_ID`    VARCHAR(100) NOT NULL,
`USER_ID`   VARCHAR(100) NOT NULL,
`ACCESS_TOKEN`  VARCHAR(255) NOT null,
`CLIENT_NONCE`  VARCHAR(255) NOT null,
`CREATE_TS`  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 CONSTRAINT `TB_ASMI_APP_ACCESS_TOKEN_PK` PRIMARY KEY (`APP_ID`,`USER_ID`,`ACCESS_TOKEN`,`CLIENT_NONCE`)
);

DROP TABLE IF EXISTS `TB_ASHS_ROLE_CONTROLS`;
CREATE TABLE `TB_ASHS_ROLE_CONTROLS` (
   `APP_ID` VARCHAR(100) NOT NULL,
   `ROLE_ID` VARCHAR(100) NOT NULL,
   `CONTROL_ID` VARCHAR(100) NOT NULL,
   `CREATED_BY` VARCHAR(100) DEFAULT NULL,
   `CREATED_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
   `VERSION_NO` int(10) DEFAULT 1,
   PRIMARY KEY (`APP_ID`,`ROLE_ID`,`CONTROL_ID`,`VERSION_NO`)
) ;

DROP TABLE IF EXISTS `TB_ASMI_USER_APP_ACCESS`;
CREATE TABLE `TB_ASMI_USER_APP_ACCESS` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `USER_ID` VARCHAR(100) NOT NULL,
  `ALLOWED_APP_ID` VARCHAR(100) NOT NULL,
  `APP_ACCESS` VARCHAR(1) DEFAULT 'D',
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` INT(10) DEFAULT 1,
  CONSTRAINT `TB_ASMI_USER_APP_ACCESS_PK` PRIMARY KEY (`APP_ID`, `USER_ID`, `ALLOWED_APP_ID`)
 ) ;
 
DROP TABLE IF EXISTS `TB_ASHS_USER_APP_ACCESS`;
CREATE TABLE `TB_ASHS_USER_APP_ACCESS` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `USER_ID` VARCHAR(100) NOT NULL,
  `ALLOWED_APP_ID` VARCHAR(100) NOT NULL,
  `APP_ACCESS` VARCHAR(1) DEFAULT 'D',
  `CREATE_USER_ID` VARCHAR(100) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` INT(10) DEFAULT 1,
  CONSTRAINT `TB_ASHS_USER_APP_ACCESS_PK` PRIMARY KEY (`APP_ID`, `USER_ID`, `ALLOWED_APP_ID`,`VERSION_NO`)
 ) ;


 DROP TABLE IF EXISTS `TB_ASMI_APP_MASTER`;
   CREATE TABLE `TB_ASMI_APP_MASTER` 
   (	
	`APP_ID` VARCHAR(100) NOT NULL,
	`PARENT_APPID` VARCHAR(100) NULL,
	`APP_NAME` VARCHAR(100) NOT NULL,
    `CONTAINER_APP` VARCHAR(1),
    `OTA_REQ` VARCHAR(1),
	`REMOTE_DEBUG` VARCHAR(1),
	`EXPIRY_DATE` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	`APP_DESCRIPTION` VARCHAR(200),
	`DEFAULT_LANGUAGE` VARCHAR(20),
	`CREATE_USER_ID` VARCHAR(20),
	`CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	`VERSION_NO` int(11) DEFAULT 1,
	`BASE_APP` VARCHAR(1),
    `MICRO_APP_TYPE` VARCHAR(10),
    `PRIMARY_MICRO_APP` VARCHAR(1) DEFAULT 'N',
    `APP_ICON` longtext,
    `APP_VERSION` VARCHAR(20) NOT NULL,
    `IDE_VERSION` VARCHAR(20) NOT NULL,
    `MAKER_ID` VARCHAR(45),
	`MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	`CHECKER_ID` VARCHAR(45),
	`CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
	`AUTH_STATUS` VARCHAR(45) DEFAULT 'U',
    `WELCOME_MSG` VARCHAR(255),
    `ANDROID_SIGNATURE` NVARCHAR(200),
	CONSTRAINT `TB_ASMI_APP_MASTER_PK` PRIMARY KEY (`APP_ID`)
   ) ;
   
  DROP TABLE IF EXISTS `TB_ASNF_APP_OS_NOTIF_CODE`; 
  CREATE TABLE TB_ASNF_APP_OS_NOTIF_CODE(
    `APP_ID` VARCHAR(100) NOT NULL,
    `OS_ID` VARCHAR(45),
    `NOTIF_CODE` VARCHAR(255),
    `ACTION_CODE` VARCHAR(255),
    `ACTION_DISPLAY` VARCHAR(255),
	`CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
   CONSTRAINT `TB_ASNF_APP_OS_NOTIF_CODE_PK` PRIMARY KEY(`APP_ID`, `OS_ID`, `NOTIF_CODE`, `ACTION_CODE`)
   );


DROP TABLE IF EXISTS `TB_ASMI_DEVICE_GRPS`;

CREATE TABLE `TB_ASMI_DEVICE_GRPS` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `DEVICE_GROUP_ID` VARCHAR(100) NOT NULL,
  `DEVICE_GROUP_DESCRIPTION` VARCHAR(1000) NOT NULL,
  `OS` VARCHAR(10) NOT NULL,
  `HEIGHT` int(10) NOT NULL,
  `WIDTH` int(10) NOT NULL,
  `ORIENTATION_LOCK` VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (`APP_ID`,`DEVICE_GROUP_ID`)
) ;


DROP TABLE IF EXISTS `TB_ASMI_SCREEN_LAYOUTS`;
CREATE TABLE `TB_ASMI_SCREEN_LAYOUTS` (
  `APP_ID` VARCHAR(6) NOT NULL,
  `SCREEN_ID` VARCHAR(100) NOT NULL,
  `LAYOUT_ID` VARCHAR(100) NOT NULL,
  `LAYOUT_NAME` VARCHAR(100) NOT NULL,
  `LAYOUT_ICON` longtext,
  `DEFAULT_TEMPLATE` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`APP_ID`,`SCREEN_ID`,`LAYOUT_ID`)
) ;

DROP TABLE IF EXISTS `TB_ASMI_SCREEN_MICRO_APP`;

CREATE TABLE `TB_ASMI_SCREEN_MICRO_APP` (
  `APP_ID` VARCHAR(6) NOT NULL,
  `SCREEN_ID` VARCHAR(100) NOT NULL,
  `MICRO_APP_ID` VARCHAR(6) NOT NULL,
  `CREATE_TS` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`APP_ID`,`SCREEN_ID`,`MICRO_APP_ID`)
) ;

DROP TABLE IF EXISTS `TB_ASMI_SCREEN_WIDGETS`;

CREATE TABLE `TB_ASMI_SCREEN_WIDGETS` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `SCREEN_ID` VARCHAR(100) NOT NULL,
  `CALLFORM_ID` VARCHAR(100) NOT NULL,
  `CREATE_TS` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`APP_ID`,`SCREEN_ID`,`CALLFORM_ID`)
) ;


DROP TABLE IF EXISTS `TB_ASMI_DESIGN_OBJECTS`;

CREATE TABLE `TB_ASMI_DESIGN_OBJECTS` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `SCREEN_ID` VARCHAR(100) NOT NULL,
  `LAYOUT_ID` VARCHAR(100) NOT NULL,
  `DESIGN_ID` VARCHAR(100) NOT NULL,
  `PARENT_ID` VARCHAR(100) NOT NULL,
  `CHILD_ID` VARCHAR(100) NOT NULL,
  `CHILD_SEQ` int(10) NOT NULL,
  PRIMARY KEY (`APP_ID`,`SCREEN_ID`,`LAYOUT_ID`,`DESIGN_ID`,`PARENT_ID`,`CHILD_ID`)
) ;


DROP TABLE IF EXISTS `TB_ASCZ_SCREEN_LAYOUTS`;

CREATE TABLE `TB_ASCZ_SCREEN_LAYOUTS` (
  `APP_ID` varchar(6) NOT NULL,
  `SCREEN_ID` VARCHAR(100) NOT NULL,
  `LAYOUT_ID` VARCHAR(100) NOT NULL,
  `DEFAULT_TEMPLATE` VARCHAR(100) NOT NULL,
  `CREATE_TS` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `MAKER_ID` VARCHAR(45),
  `MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `CHECKER_ID` VARCHAR(45),
  `CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `AUTH_STATUS` VARCHAR(1) DEFAULT 'U',
  `VERSION_NO` int(11) DEFAULT 1,
  PRIMARY KEY (`APP_ID`,`SCREEN_ID`,`LAYOUT_ID`)
) ;


DROP TABLE IF EXISTS `TB_ASCZ_TEMPLATE_OBJECTS`;

CREATE TABLE `TB_ASCZ_TEMPLATE_OBJECTS` (
  `APP_ID` VARCHAR(6) NOT NULL,
  `SCREEN_ID` VARCHAR(100) NOT NULL,
  `LAYOUT_ID` VARCHAR(100) NOT NULL,
  `TEMPLATE_ID` VARCHAR(100) NOT NULL,
  `PARENT_ID` VARCHAR(100) NOT NULL,
  `CHILD_ID` VARCHAR(100) NOT NULL,
  `CHILD_SEQ` int(10) NOT NULL,
  PRIMARY KEY (`APP_ID`,`SCREEN_ID`,`LAYOUT_ID`,`TEMPLATE_ID`,`PARENT_ID`,`CHILD_ID`)
) ;



DROP TABLE IF EXISTS `TB_ASTP_SESSION_STORAGE`;

CREATE TABLE `TB_ASTP_SESSION_STORAGE`(
`APP_ID` VARCHAR(100) NOT NULL,
`USER_ID` VARCHAR(100) NOT NULL,
`SESSION_ID` VARCHAR(255) NOT NULL,
`DEVICE_ID` VARCHAR(255) NULL,
`SESSION_KEY` VARCHAR(255) NOT NULL,
`SESSION_VALUE` LONGTEXT NOT NULL,
`CREATED_BY` VARCHAR(100) NULL,
`CREATE_TS` timestamp(3) DEFAULT current_timestamp(3),
PRIMARY KEY (`APP_ID`,`USER_ID`,`SESSION_ID`, `SESSION_KEY`)
);

DROP TABLE IF EXISTS `TB_DBTP_TXN_MASTER`;

CREATE TABLE `TB_DBTP_TXN_MASTER` (
  `TXN_REF_NO` VARCHAR(255) NOT NULL,
  `APP_ID` VARCHAR(6) NOT NULL,
  `USER_ID` VARCHAR(100) NOT NULL,
  `CUSTOMER_ID` VARCHAR(100) NOT NULL,
  `AMOUNT` DECIMAL(22,3) NOT NULL,
  `TXN_TYPE` VARCHAR(20) NOT NULL,
  `TXN_STATUS` VARCHAR(1) DEFAULT 'U',
  `CREATION_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `COMPLETION_TS` TIMESTAMP(3) NULL,
  PRIMARY KEY (`TXN_REF_NO`)
);

DROP TABLE IF EXISTS `TB_ASLG_DEVICE_LOCATION`;

CREATE TABLE `TB_ASLG_DEVICE_LOCATION` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `DEVICE_ID` VARCHAR(255) NOT NULL,
  `LATITUDE` VARCHAR(255) DEFAULT NULL,
  `LONGITUDE` VARCHAR(255) DEFAULT NULL,
  `CREATE_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
   PRIMARY KEY (`APP_ID`,`DEVICE_ID`)
 );

DROP TABLE IF EXISTS `TB_ASMI_CAPTCHA_DTLS`;

CREATE TABLE `TB_ASMI_CAPTCHA_DTLS` (
  `CAPTCHA_REF` BIGINT NOT NULL,
  `APP_ID` varchar(100) ,
  `CAPTCHA_STRING` varchar(255),
  `AUDIO_CAPTCHA` varchar(255),
  `INTERFACE_ID` varchar(100) ,
  `SESSION_ID` varchar(255),
  `CREATE_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `VALIDATE_TS` TIMESTAMP(3) NULL,
  `CAPTCHA_STATUS` VARCHAR(2) DEFAULT 'NP',
   `VERSION_NO` int(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (`CAPTCHA_REF`)
); 

DROP TABLE IF EXISTS `TB_ASMI_CNVUI_MASTER`;

CREATE TABLE `TB_ASMI_CNVUI_MASTER` (
  `APP_ID` varchar(100) NOT NULL,
  `CNVUI_ID` varchar(100) NOT NULL,
  `CNVUI_DESC` varchar(100),
  `CREATE_USER_ID` varchar(100) DEFAULT NULL,
  `CREATE_TS` timestamp(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  CONSTRAINT `TB_ASMI_CNVUI_MASTER_PK` PRIMARY KEY (`APP_ID`,`CNVUI_ID`)
);

DROP TABLE IF EXISTS `TB_ASMI_DLG_MASTER`;

CREATE TABLE `TB_ASMI_DLG_MASTER` (
  `APP_ID` varchar(100) NOT NULL,
  `CNVUI_ID` varchar(100) NOT NULL,
  `DLG_ID` varchar(100) NOT NULL,
  `DLG_DESC` varchar(100),
  `DLG_TYPE` varchar(100),
  `DLG_SEQ` int(10),
  `NXT_DLG_ID` varchar(100),
  `RESP_DLG_ID` varchar(100),
  `RESP_TYPE` varchar(100),
  `SCREEN_ID` varchar(100),
  `INTERFACE_ID` varchar(100),
  `CREATE_USER_ID` varchar(100) DEFAULT NULL,
  `CREATE_TS` timestamp(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `MAKER_ID` VARCHAR(45),
  `MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `CHECKER_ID` VARCHAR(45),
  `CHECKER_TS` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `AUTH_STATUS` VARCHAR(1) DEFAULT 'U',
  `VERSION_NO` int(10) DEFAULT 1,
  CONSTRAINT `TB_ASMI_DLG_MASTER_PK` PRIMARY KEY (`APP_ID`,`CNVUI_ID`,`DLG_ID`)
);

DROP TABLE IF EXISTS `TB_ASMI_CNVUI_SCR`;

CREATE TABLE `TB_ASMI_CNVUI_SCR` (
  `APP_ID` varchar(100) NOT NULL,
  `SCREEN_ID` varchar(100) NOT NULL,
  `SCREEN_DESC` varchar(100),
  `SCREEN_DEF` LONGTEXT,
  `SCREEN_DESIGN` LONGTEXT,
  `SCREEN_HTML` LONGTEXT,
  `SCREEN_LAYOUT` LONGTEXT,
  `TEMPLATE` LONGTEXT,
  `CREATE_USER_ID` varchar(100) DEFAULT NULL,
  `CREATE_TS` timestamp(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(10) DEFAULT 1,
  CONSTRAINT `TB_ASMI_CNVUI_SCR_PK` PRIMARY KEY (`APP_ID`,`SCREEN_ID`)
);

DROP TABLE IF EXISTS `TB_ASLG_CNVUI_TXN_LOG`;

CREATE TABLE `TB_ASLG_CNVUI_TXN_LOG` (
  `TXN_REF` varchar(255) NOT NULL,
  `APP_ID` varchar(100),
  `CNVUI_ID` varchar(100),
  `RESP_DLG_ID` varchar(100),
  `SCREEN_DATA` LONGTEXT,
  `CREATE_USER_ID` varchar(100) DEFAULT NULL,
  `CREATE_TS` timestamp(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `UPDATE_TS` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT `TB_ASLG_CNVUI_TXN_LOG_PK` PRIMARY KEY (`TXN_REF`)
);


DROP TABLE IF EXISTS `TB_ASMI_CS_NONCEDETAILS`;


CREATE TABLE `TB_ASMI_CS_NONCEDETAILS` (
`DEVICE_ID` VARCHAR(100),
`APP_ID` VARCHAR(100),
`REQUEST_ID` VARCHAR(255),
`CLIENT_NONCE` VARCHAR(100),
`SERVER_NONCE` VARCHAR(100),
`STATUS` VARCHAR(100),
`SERVER_TOKEN` VARCHAR(100),
`CREATE_TS` timestamp(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
`CREATED_ON` DATE
)
/* this partition by key, partition by key is not available in mysql DB */
PARTITION BY KEY(DEVICE_ID)
PARTITIONS 64;


create unique index TB_ASMI_CS_NONCEDETAILS_IDX01 on TB_ASMI_CS_NONCEDETAILS(DEVICE_ID, APP_ID, REQUEST_ID, CLIENT_NONCE, SERVER_NONCE);


DROP TABLE if exists `TB_ASMI_WORKFLOW_DEFN`;

CREATE TABLE `TB_ASMI_WORKFLOW_DEFN` (
	`APP_ID` VARCHAR(100) NOT NULL,
	`WORKFLOW_ID` VARCHAR(100) NOT NULL,
	`WORKFLOW_DESC` VARCHAR(255),
	`VERSION_NO` int(10),
	`MAKER_ID` VARCHAR(255),
	`MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	`CHECKER_ID` VARCHAR(255),
	`CHECKER_TS` TIMESTAMP(3) NULL,
	`AUTH_STATUS` VARCHAR(1),
	`ACTIVE` CHAR(1),
	`TXN_TYPE` VARCHAR(100),
	`ONCE_AUTH` VARCHAR(1),
	PRIMARY KEY (`APP_ID`, `WORKFLOW_ID`)
);


DROP TABLE if exists `TB_ASMI_WORKFLOW_RULES`;

CREATE TABLE `TB_ASMI_WORKFLOW_RULES`(
	`APP_ID` VARCHAR(100) NOT NULL,
	`WORKFLOW_ID` VARCHAR(100) NOT NULL,
	`RULE_ID` VARCHAR(50) NOT NULL,
	`RULE_DESC` VARCHAR(255),
	`RULE_BEAN` VARCHAR(255),	
	`VERSION_NO` int(10),
	`MAKER_ID` VARCHAR(45),
	`MAKER_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	`CHECKER_ID` VARCHAR(45),
	`CHECKER_TS` TIMESTAMP(3) NULL,
	`AUTH_STATUS` VARCHAR(1),
	`ACTIVE` CHAR(1),
	`ONCE_AUTH` VARCHAR(1),
	
	PRIMARY KEY (`APP_ID`, `RULE_ID`, `WORKFLOW_ID`)
);

DROP TABLE if exists `TB_ASMI_WORKFLOW_STAGES`;

CREATE TABLE `TB_ASMI_WORKFLOW_STAGES` (
	`APP_ID` VARCHAR(100) NOT NULL,
	`WORKFLOW_ID` VARCHAR(100) NOT NULL,
	`STAGE_ID` VARCHAR(50) NOT NULL,
	`STAGE_SEQ_NO` int(10),
	`STAGE_TYPE` VARCHAR(50),
	`STAGE_DESC` VARCHAR(255),
	`RULE_ID` VARCHAR(50),
	`SCREEN_ID` VARCHAR(50),
	`IS_AUTH_MATRIX_REQD` VARCHAR(1),
	PRIMARY KEY (`APP_ID`, `STAGE_ID`, `WORKFLOW_ID`)
);

DROP TABLE if exists `TB_ASTP_WORKFLOW_TXN_DETAIL`;

CREATE TABLE `TB_ASTP_WORKFLOW_TXN_DETAIL` (
	`APP_ID` VARCHAR(100) NOT NULL,
	`WORKFLOW_REF_NO` VARCHAR(100) NOT NULL,
	`STAGE_ID` VARCHAR(50) NOT NULL,
	`WORKFLOW_ID` VARCHAR(100),
	`WORKFLOW_SEQ_NO` int(10) ,
	`TASK_DATA` longtext,
	`USER_ID` VARCHAR(50),
	`STATUS` VARCHAR(50),
	`UPDATED_NEXT_STAGES` VARCHAR(255),
	`LAST_EVENT_NO` int(10),
	`START_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	`END_TS` TIMESTAMP(3) NULL,
	`REMARKS` VARCHAR(255),
	`CUSTOM_FIELD_1` VARCHAR(100),
	`CUSTOM_FIELD_2` VARCHAR(100),
	`CUSTOM_FIELD_3` VARCHAR(100),
	`CUSTOM_FIELD_4` VARCHAR(100),
	`CUSTOM_FIELD_5` VARCHAR(100),	
	PRIMARY KEY (`APP_ID`, `WORKFLOW_REF_NO`, `WORKFLOW_SEQ_NO`)
);

DROP TABLE if exists `TB_ASTP_WORKFLOW_EVENT`;

CREATE TABLE `TB_ASTP_WORKFLOW_EVENT` (
	`APP_ID` VARCHAR(100) NOT NULL,
	`WORKFLOW_REF_NO` VARCHAR(100) NOT NULL,
	`WORKFLOW_SEQ_NO` int(10) NOT NULL,
	`EVENT_SEQ_NO` int(10) NOT NULL,
	`WORKFLOW_ID` VARCHAR(100),
	`STAGE_ID` VARCHAR(50) NOT NULL,
	`EVENT_ID` VARCHAR(50),
	`TASK_DATA` longtext,
	`USER_ID` VARCHAR(50),
	`EVENT_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	`REMARKS` VARCHAR(255),
	`CUSTOM_FIELD_1` VARCHAR(100),
	`CUSTOM_FIELD_2` VARCHAR(100),
	`CUSTOM_FIELD_3` VARCHAR(100),
	`CUSTOM_FIELD_4` VARCHAR(100),
	`CUSTOM_FIELD_5` VARCHAR(100),	
	PRIMARY KEY (`APP_ID`, `WORKFLOW_REF_NO`, `WORKFLOW_SEQ_NO`, `EVENT_SEQ_NO`)
);

DROP TABLE if exists `TB_ASTP_WORKFLOW_TXN_MASTER`;

CREATE TABLE `TB_ASTP_WORKFLOW_TXN_MASTER` (
	`APP_ID` VARCHAR(100) NOT NULL,
	`WORKFLOW_REF_NO` VARCHAR(100) NOT NULL,
	`WORKFLOW_ID` VARCHAR(100),
	`STATUS` VARCHAR(50),
	`START_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	`MODIFIED_TS` TIMESTAMP(3) NULL ON UPDATE CURRENT_TIMESTAMP(3),
	`END_TS` TIMESTAMP(3) NULL,
	`CUSTOM_FIELD_1` VARCHAR(100),
	`CUSTOM_FIELD_2` VARCHAR(100),
	`CUSTOM_FIELD_3` VARCHAR(100),
	`CUSTOM_FIELD_4` VARCHAR(100),
	`CUSTOM_FIELD_5` VARCHAR(100),
	PRIMARY KEY (`APP_ID`, `WORKFLOW_REF_NO`)
);

DROP TABLE if exists `TB_ASHS_WORKFLOW_TXN_DETAILS`;

CREATE TABLE `TB_ASHS_WORKFLOW_TXN_DETAILS` (
	`APP_ID` VARCHAR(100) NOT NULL,
	`WORKFLOW_REF_NO` VARCHAR(100) NOT NULL,
	`WORKFLOW_SEQ_NO` int(10) NOT NULL,
	`WORKFLOW_ID` VARCHAR(100),
	`STAGE_ID` VARCHAR(50),
	`TASK_DATA` longtext,
	`USER_ID` VARCHAR(50),
	`STATUS` VARCHAR(50),
	`UPDATED_NEXT_STAGES` VARCHAR(255),
	`LAST_ACTION` VARCHAR(50),
	`CUSTOM_FIELD_1` VARCHAR(100),
	`CUSTOM_FIELD_2` VARCHAR(100),
	`CUSTOM_FIELD_3` VARCHAR(100),
	`CUSTOM_FIELD_4` VARCHAR(100),
	`CUSTOM_FIELD_5` VARCHAR(100),	
	PRIMARY KEY (`APP_ID`, `WORKFLOW_REF_NO`, `WORKFLOW_SEQ_NO`)
);


DROP TABLE if exists `TB_ASHS_WORKFLOW_TXN_MASTER`;

CREATE TABLE `TB_ASHS_WORKFLOW_TXN_MASTER` (
	`APP_ID` VARCHAR(100) NOT NULL,
	`WORKFLOW_REF_NO` VARCHAR(100) NOT NULL,
	`WORKFLOW_ID` VARCHAR(100),
	`STATUS` VARCHAR(50),
	`START_TS` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	`MODIFIED_TS` TIMESTAMP(3) NULL ON UPDATE CURRENT_TIMESTAMP(3),
	`END_TS` TIMESTAMP(3) NULL,
	`CUSTOM_FIELD_1` VARCHAR(100),
	`CUSTOM_FIELD_2` VARCHAR(100),
	`CUSTOM_FIELD_3` VARCHAR(100),
	`CUSTOM_FIELD_4` VARCHAR(100),
	`CUSTOM_FIELD_5` VARCHAR(100),	
	PRIMARY KEY (`APP_ID`, `WORKFLOW_REF_NO`)
);


DROP TABLE if exists `TB_ASMI_WORKFLOW_LINKED_STAGES`;

CREATE TABLE `TB_ASMI_WORKFLOW_LINKED_STAGES` (
	`APP_ID` VARCHAR(100) NOT NULL,
	`WORKFLOW_ID` VARCHAR(100),
	`STAGE_ID` VARCHAR(50),
	`LINKAGE_TYPE` char(1),
	`LINKED_STAGE_ID` VARCHAR(50),
	PRIMARY KEY (`APP_ID`, `LINKAGE_TYPE`, `LINKED_STAGE_ID`, `STAGE_ID`, `WORKFLOW_ID`)
);

DROP TABLE if exists `TB_ASMI_ROLE_WORKFLOWS`;

CREATE TABLE `TB_ASMI_ROLE_WORKFLOWS`(
`APP_ID` VARCHAR(100) NOT NULL,	
`ROLE_ID` VARCHAR(100) NOT NULL,	
`WORKFLOW_ID` VARCHAR(100) NOT NULL,	
`STAGE_ID` VARCHAR(50) NOT NULL,		
PRIMARY KEY (`APP_ID`, `ROLE_ID`, `WORKFLOW_ID`, `STAGE_ID`)
);

DROP TABLE IF EXISTS `TB_ASMI_COOKIES`;

CREATE TABLE `TB_ASMI_COOKIES` (
  `APP_ID` VARCHAR(100) NOT NULL,
  `USER_ID` VARCHAR(100) NOT NULL,
  `USR_SELECTOR` VARCHAR(50) NOT NULL,
  `USR_VALIDATOR` VARCHAR(255) NOT NULL,
  `CREATE_TS` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `EXPIRY_TS` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `VERSION_NO` int(11) DEFAULT 1,
  PRIMARY KEY (`APP_ID`,`USR_SELECTOR`) 
);

CREATE OR REPLACE VIEW VW_LOCATION_DETAILS
AS
SELECT * FROM TB_ASTP_LAST_LOGIN A where A.SESSION_ID IS NOT NULL
AND sysdate() - A.LAST_REQ_TIME < (SELECT SESSION_TIMEOUT FROM TB_ASMI_SECURITY_PARAMETERS C WHERE A.APP_ID=C.APP_ID );

CREATE OR REPLACE VIEW VW_ACTIVE_SESSIONS AS
SELECT B.OS, A.APP_ID, COUNT(*) as COUNT
FROM TB_ASTP_LAST_LOGIN A,TB_ASMI_DEVICE_MASTER B
WHERE A.APP_ID =B.APP_ID
AND A.DEVICE_ID = B.DEVICE_ID
AND A.SESSION_ID IS NOT NULL
AND sysdate() - LAST_REQ_TIME < (SELECT SESSION_TIMEOUT FROM TB_ASMI_SECURITY_PARAMETERS C WHERE A.APP_ID=C.APP_ID )
GROUP BY B.OS,A.APP_ID
union all
SELECT A.DEVICE_ID,A.APP_ID, COUNT(*) as COUNT
FROM TB_ASTP_LAST_LOGIN A
WHERE A.DEVICE_ID IN ('WEB','SIMULATOR')
AND A.SESSION_ID IS NOT NULL
AND sysdate() - A.LAST_REQ_TIME < (SELECT SESSION_TIMEOUT FROM TB_ASMI_SECURITY_PARAMETERS C WHERE A.APP_ID=C.APP_ID )
GROUP BY A.DEVICE_ID,A.APP_ID;

CREATE OR REPLACE VIEW VW_ACTIVE_INACTIVE_USERS
AS
SELECT t1.APP_ID, date(t1.CREATE_TS) as CREATE_TS, count(*) as ACTIVE , 0 INACTIVE
FROM TB_ASMI_USER t1
LEFT JOIN TB_ASTP_LAST_LOGIN t2 ON t2.USER_ID = t1.USER_ID AND t2.APP_ID = t1.APP_ID 
WHERE t2.USER_ID IS NOT NULL AND t1.USER_ACTIVE='Y'
GROUP BY t1.APP_ID, date(t1.CREATE_TS)
UNION ALL
SELECT t1.APP_ID,date(t1.CREATE_TS) as CREATE_TS, 0 ACTIVE, count(*) as INACTIVE
FROM TB_ASMI_USER t1
LEFT JOIN TB_ASTP_LAST_LOGIN t2 ON t2.USER_ID = t1.USER_ID AND t2.APP_ID = t1.APP_ID 
WHERE t2.USER_ID IS NULL AND t1.USER_ACTIVE='Y'
GROUP BY t1.APP_ID, date(t1.CREATE_TS);

CREATE OR REPLACE VIEW VW_LOGIN_REPORT 
AS
SELECT tb.APP_ID,tb.DEVICE_ID,date(tb.CREATE_TS) as AccessDate,count(*) as TotalTxns,0 Logins,0 DistinctLogins
FROM  TB_ASLG_TXN_DETAIL tb WHERE tb.TXN_STAT='S'
GROUP BY tb.APP_ID,tb.DEVICE_ID,date(tb.CREATE_TS)
UNION ALL
SELECT tb2.APP_ID,tb2.DEVICE_ID,date(tb2.CREATE_TS) as AccessDate,0 TotalTxns,count(*) as Logins,
count(distinct date(tb2.CREATE_TS)) as DistinctLogins
FROM TB_ASLG_TXN_DETAIL tb2 WHERE 
(tb2.INTERFACE_ID='appzillonReLoginRequest' OR tb2.INTERFACE_ID='appzillonAuthenticationRequest')
and tb2.TXN_STAT='S' 
GROUP BY tb2.APP_ID,tb2.USER_ID,tb2.DEVICE_ID,date(tb2.CREATE_TS);

CREATE OR REPLACE VIEW VW_CUSTOMER_REPORT
AS
SELECT tb.APP_ID,tb.USER_ID,tb.SESSION_ID,
MAX(CAST(UNIX_TIMESTAMP(END_TM) *1000 AS UNSIGNED)) - MIN(CAST(UNIX_TIMESTAMP(ST_TM) *1000 AS UNSIGNED))tm,
count(*) as TotalTxns,
count(distinct(tb.INTERFACE_ID)) as DistinctTxns, 0 Logins,0 DistinctLogins
FROM  TB_ASLG_TXN_DETAIL tb WHERE tb.TXN_STAT='S' GROUP BY tb.APP_ID, tb.USER_ID,tb.SESSION_ID
UNION ALL
SELECT tb2.APP_ID,tb2.USER_ID, null SESSION_ID, null tm,
0 TotalTxns,0 DistinctTxns,count(*) as Logins,
count(distinct date(tb2.CREATE_TS)) as DistinctLogins
FROM TB_ASLG_TXN_DETAIL tb2 WHERE 
(tb2.INTERFACE_ID='appzillonReLoginRequest' OR tb2.INTERFACE_ID='appzillonAuthenticationRequest')
and tb2.TXN_STAT='S' GROUP BY tb2.APP_ID, tb2.USER_ID;

CREATE OR REPLACE VIEW VW_LAT_LON_DETAILS
AS
SELECT APP_ID,USER_ID,COUNT(LONGITUDE) as COUNT_LON, LONGITUDE, 
COUNT(LATITUDE) as COUNT_LAT,LATITUDE, FORMATTED_ADDRESS FROM TB_ASLG_TXN_DETAIL GROUP BY LONGITUDE, LATITUDE, FORMATTED_ADDRESS, APP_ID, USER_ID;

CREATE OR REPLACE VIEW VW_CUSTOMER_DETAILS AS
SELECT APP_ID,USER_ID,DATE(CREATE_TS) AS AccessDate,SESSION_ID,min(ST_TM) as ST_TM,max(END_TM) as END_TM,Count(*) As 
TotalTxns,0 DistinctTxns,LATITUDE,LONGITUDE,FORMATTED_ADDRESS 
FROM TB_ASLG_TXN_DETAIL
WHERE TXN_STAT='S' 
GROUP BY APP_ID,USER_ID,DATE(CREATE_TS),SESSION_ID,LATITUDE,LONGITUDE,FORMATTED_ADDRESS
Union ALL
SELECT APP_ID,USER_ID,DATE(CREATE_TS) AS AccessDate,SESSION_ID,min(ST_TM) as ST_TM,max(END_TM) as END_TM,0 TotalTxns, 
Count(distinct(INTERFACE_ID)) AS DistinctTxns,LATITUDE,LONGITUDE,FORMATTED_ADDRESS
FROM TB_ASLG_TXN_DETAIL
WHERE TXN_STAT='S'
GROUP by APP_ID,USER_ID,DATE(CREATE_TS),SESSION_ID,INTERFACE_ID,LATITUDE,LONGITUDE,FORMATTED_ADDRESS;

CREATE OR REPLACE VIEW VW_TXN_APP_USAGE AS
SELECT txn.APP_ID,DATE(txn.CREATE_TS) AS AccessDate,intf.DESCRIPTION, txn.TXN_STAT, 
CAST(MIN(CAST(UNIX_TIMESTAMP(txn.END_TM)*1000 AS unsigned) - CAST(UNIX_TIMESTAMP(txn.ST_TM)*1000 AS unsigned))AS unsigned) AS MinTime,
CAST(MAX(CAST(UNIX_TIMESTAMP(txn.END_TM)*1000 AS unsigned) - CAST(UNIX_TIMESTAMP(txn.ST_TM)*1000 AS unsigned)) AS unsigned) AS MaxTime, 
CAST(AVG(CAST(UNIX_TIMESTAMP(txn.END_TM)*1000 AS unsigned) - CAST(UNIX_TIMESTAMP(txn.ST_TM)*1000 AS unsigned)) AS unsigned) AS AvgTime, 
count(txn.INTERFACE_ID) AS IntfCount
FROM TB_ASLG_TXN_DETAIL txn, TB_ASMI_INTF_MASTER intf 
WHERE txn.INTERFACE_ID = intf.INTERFACE_ID
GROUP BY txn.APP_ID,txn.INTERFACE_ID,DATE(txn.CREATE_TS),intf.DESCRIPTION,txn.TXN_STAT;

CREATE OR REPLACE VIEW VW_ASMI_DEVICE_GRPS AS
SELECT APP_ID, DEVICE_GROUP_ID, DEVICE_GROUP_DESCRIPTION, OS,HEIGHT, WIDTH, 'PORTRAIT' AS ORIENTATION
FROM TB_ASMI_DEVICE_GRPS WHERE ORIENTATION_LOCK = 'ANY'
UNION ALL
SELECT APP_ID, DEVICE_GROUP_ID, DEVICE_GROUP_DESCRIPTION, OS,HEIGHT, WIDTH, 'LANDSCAPE' AS ORIENTATION
FROM TB_ASMI_DEVICE_GRPS WHERE ORIENTATION_LOCK = 'ANY'
UNION ALL
SELECT APP_ID, DEVICE_GROUP_ID, DEVICE_GROUP_DESCRIPTION, OS,HEIGHT, WIDTH, ORIENTATION_LOCK AS ORIENTATION
FROM TB_ASMI_DEVICE_GRPS WHERE ORIENTATION_LOCK != 'ANY';

CREATE OR REPLACE VIEW VW_ASMI_MICROAPPS AS
SELECT T2.APP_ID AS APP_ID, T2.SCREEN_ID, T2.MICRO_APP_ID AS MICRO_APP_ID, T1.APP_NAME AS MICRO_APP_NAME, T1.APP_ICON AS MICRO_APP_ICON,
T1.MICRO_APP_TYPE AS MICRO_APP_TYPE FROM TB_ASMI_APP_MASTER T1, TB_ASMI_SCREEN_MICRO_APP T2
WHERE T1.APP_ID = T2.MICRO_APP_ID AND T1.BASE_APP = 'N';

CREATE OR REPLACE VIEW VW_ASMI_NANOAPPS AS
SELECT T1.APP_ID, T2.SCREEN_ID, T1.SCREEN_ID AS CALLFORM_ID, T1.SCREEN_NAME AS CALLFORM_NAME, T1.SCREEN_ICON AS CALLFORM_ICON
FROM TB_ASMI_SCR_MASTER T1, TB_ASMI_SCREEN_WIDGETS T2
WHERE T1.APP_ID = T2.APP_ID AND T1.SCREEN_ID = T2.CALLFORM_ID AND T1.SCREEN_TYPE = 'CALL';
